version: '3.8'

services:
  chrome:
    image: kasmweb/chrome:latest
    container_name: kasm-chrome
    environment:
      - VNC_PW=password  # Set a VNC password
      - RESOLUTION=1280x1024  # Set the desired screen resolution
      - KASM_PORT=6901
    ports:
      - "6901:6901"  # Web interface port for noVNC
      - "5900:5900"  # VNC port
    volumes:
      - data:/data
    restart: unless-stopped

volumes:
  data:
