version: "3.8"

services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: chris-store-pher-chrome
      APP_PORT: 6901
  nginx:
    image: nginx:alpine
    command: [nginx-debug, "-g", "daemon off;"]
    ports:
      - "8081:80"  # Changed to 8081 to avoid conflict with port 80

  chrome:
    image: kasmweb/chrome:1.13.0
    environment:
      - VNC_PW=password  # Set a VNC password
      - RESOLUTION=1280x1024  # Set the desired screen resolution
      - KASM_PORT=6901
    ports:
      - "6901:6901"  # Web interface port for noVNC
      - "5901:5900"  # VNC port, changed to avoid conflict with 5900
    volumes:
      - data:/data
    restart: unless-stopped

volumes:
  data:
