version: "2"
services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: chris-store-pher-chrome
      APP_PORT: 6901
  nginx:
    image: nginx:alpine
    command: [nginx-debug, "-g", "daemon off;"]
    ports:
      - 80:80

  chrome:
    image: kasmweb/chrome:latest
    environment:
      - VNC_PW=password
      - RESOLUTION=1280x1024
      - KASM_PORT=6901
    ports:
      - "6901:6901"
      - "5900:5900"
    volumes:
      - data:/data
    restart: unless-stopped

volumes:
  data:
