version: "2"
services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: chris-store-pher-chrome_1
      APP_PORT: 13241

  web:
    image: zenika/alpine-chrome:latest

    restart: on-failure
    stop_grace_period: 1m
    command: [chromium-browser, "--headless", "--disable-gpu", "--no-sandbox", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222"]
    ports:
      - "13241:9222"
